package chainSimulator

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io"
	"math/big"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/multiversx/mx-chain-core-go/core"
	"github.com/multiversx/mx-chain-core-go/data"
	"github.com/multiversx/mx-chain-core-go/data/block"
	hashFactory "github.com/multiversx/mx-chain-core-go/hashing/factory"
	marshalFactory "github.com/multiversx/mx-chain-core-go/marshal/factory"
	"github.com/multiversx/mx-chain-crypto-go/signing"
	"github.com/multiversx/mx-chain-crypto-go/signing/ed25519"
	"github.com/multiversx/mx-chain-crypto-go/signing/mcl"
	"github.com/multiversx/mx-chain-crypto-go/signing/secp256k1"
	"github.com/stretchr/testify/require"

	commonConfig "github.com/multiversx/mx-chain-go/common"
	"github.com/multiversx/mx-chain-go/common/enablers"
	commonFactory "github.com/multiversx/mx-chain-go/common/factory"
	"github.com/multiversx/mx-chain-go/config"
	"github.com/multiversx/mx-chain-go/genesis"
	"github.com/multiversx/mx-chain-go/genesis/parsing"
	"github.com/multiversx/mx-chain-go/node/chainSimulator/components/api"
	"github.com/multiversx/mx-chain-go/node/chainSimulator/configs"
	p2pFactory "github.com/multiversx/mx-chain-go/p2p/factory"
	"github.com/multiversx/mx-chain-go/process"
	"github.com/multiversx/mx-chain-go/sharding"
	"github.com/multiversx/mx-chain-go/sharding/nodesCoordinator"
	"github.com/multiversx/mx-chain-go/testscommon/chainParameters"
	"github.com/multiversx/mx-chain-go/testscommon/epochNotifier"
)

type s0R3SimulatorSnapshot struct {
	ValidatorPublicKeys []string          `json:"validatorPublicKeys"`
	WalletPublicKeys    []string          `json:"walletPublicKeys"`
	TerminalNonces      map[uint32]uint64 `json:"terminalNonces"`
	TerminalRounds      map[uint32]uint64 `json:"terminalRounds"`
	StateRoots          map[uint32]string `json:"stateRoots"`
}

type s0R3ProcessInventory struct {
	SchemaVersion        string               `json:"schemaVersion"`
	PackageClass         string               `json:"packageClass"`
	SourceCommit         string               `json:"sourceCommit"`
	SourceTree           string               `json:"sourceTree"`
	NodeBinarySHA256     string               `json:"nodeBinarySha256"`
	SeedBinarySHA256     string               `json:"seednodeBinarySha256"`
	ConfigurationRoot    string               `json:"configurationRoot"`
	WorkingDirConvention string               `json:"workingDirectoryConvention"`
	ChainID              string               `json:"chainID"`
	GenesisStartTime     int64                `json:"genesisStartTime"`
	Processes            []s0R3ProcessBinding `json:"processes"`
	SupportProcesses     []s0R3ProcessBinding `json:"supportProcesses"`
}

type s0R3ProcessBinding struct {
	ID               string   `json:"id"`
	Role             string   `json:"role"`
	Shard            string   `json:"shard"`
	KeyFile          string   `json:"keyFile"`
	KeyIndex         int      `json:"keyIndex"`
	P2PKeyFile       string   `json:"p2pKeyFile"`
	APIPort          int      `json:"apiPort"`
	P2PPort          int      `json:"p2pPort"`
	WorkingDirectory string   `json:"workingDirectory"`
	Argv             []string `json:"argv"`
}

func TestS0R3InternalSimulatorDeterminism(t *testing.T) {
	t.Skip("deterministic simulator key overlay is historical; current S0 uses repository-native simulator tests")
	first := runS0R3Simulator(t)
	second := runS0R3Simulator(t)
	require.Equal(t, first, second)

	encoded, err := json.Marshal(first)
	require.NoError(t, err)
	t.Logf("S0_R3_SIMULATOR_SNAPSHOT=%s", encoded)
}

func TestS0R3MaterializeNonRunningPackage(t *testing.T) {
	packageRoot := os.Getenv("S0_R3_PACKAGE_ROOT")
	if packageRoot == "" {
		t.Skip("S0_R3_PACKAGE_ROOT is required for retained package materialization")
	}
	entries, err := os.ReadDir(packageRoot)
	require.NoError(t, err)
	require.Empty(t, entries, "package root must start empty")

	// Fresh localnet keys are intentionally generated by the upstream cryptographic generator.
	materialized, err := configs.CreateChainSimulatorConfigs(configs.ArgsChainSimulatorConfigs{
		NumOfShards:                    3,
		OriginalConfigsPath:            "../../cmd/node/config/",
		RoundDurationInMillis:          6000,
		SupernovaRoundDurationInMillis: 600,
		TempDir:                        packageRoot,
		NumNodesWaitingListShard:       1,
		NumNodesWaitingListMeta:        1,
		MinNodesPerShard:               3,
		ConsensusGroupSize:             3,
		MetaChainMinNodes:              3,
		MetaChainConsensusGroupSize:    3,
		RoundsPerEpoch:                 core.OptionalUint64{HasValue: true, Value: 200},
		SupernovaRoundsPerEpoch:        core.OptionalUint64{HasValue: true, Value: 2000},
	})
	require.NoError(t, err)
	require.Len(t, materialized.ValidatorsPrivateKeys, 16)
	require.Len(t, materialized.Configs.NodesConfig.InitialNodes, 16)
	transformS0R3LocalnetConfig(t, packageRoot)
	materializeS0R3RuntimeInputs(t, packageRoot)
	t.Logf("S0_R3_NON_RUNNING_PACKAGE_ROOT=%s", packageRoot)
}

func transformS0R3LocalnetConfig(t *testing.T, packageRoot string) {
	configPath := filepath.Join(packageRoot, "config", "config.toml")
	contents, err := os.ReadFile(configPath)
	require.NoError(t, err)
	text := string(contents)
	replacements := map[string]string{
		`ChainID = "undefined"`: `ChainID = "local-testnet"`,
		`{ EnableEpoch = 0, RoundDuration = 6000, RoundsPerEpoch = 200, MinRoundsBetweenEpochs = 20, ShardConsensusGroupSize = 7, ShardMinNumNodes = 10, MetachainConsensusGroupSize = 10, MetachainMinNumNodes = 10, Hysteresis = 0.2, Adaptivity = false, Offset = 0 }`:  `{ EnableEpoch = 0, RoundDuration = 6000, RoundsPerEpoch = 200, MinRoundsBetweenEpochs = 20, ShardConsensusGroupSize = 3, ShardMinNumNodes = 3, MetachainConsensusGroupSize = 3, MetachainMinNumNodes = 3, Hysteresis = 0.0, Adaptivity = false, Offset = 0 }`,
		`{ EnableEpoch = 1, RoundDuration = 6000, RoundsPerEpoch = 200, MinRoundsBetweenEpochs = 20, ShardConsensusGroupSize = 10, ShardMinNumNodes = 10, MetachainConsensusGroupSize = 10, MetachainMinNumNodes = 10, Hysteresis = 0.2, Adaptivity = false, Offset = 0 }`: `{ EnableEpoch = 1, RoundDuration = 6000, RoundsPerEpoch = 200, MinRoundsBetweenEpochs = 20, ShardConsensusGroupSize = 3, ShardMinNumNodes = 3, MetachainConsensusGroupSize = 3, MetachainMinNumNodes = 3, Hysteresis = 0.0, Adaptivity = false, Offset = 0 }`,
		`{ EnableEpoch = 2, RoundDuration = 600, RoundsPerEpoch = 2000, MinRoundsBetweenEpochs = 50, ShardConsensusGroupSize = 10, ShardMinNumNodes = 10, MetachainConsensusGroupSize = 10, MetachainMinNumNodes = 10, Hysteresis = 0.2, Adaptivity = false, Offset = 2 }`: `{ EnableEpoch = 2, RoundDuration = 600, RoundsPerEpoch = 2000, MinRoundsBetweenEpochs = 50, ShardConsensusGroupSize = 3, ShardMinNumNodes = 3, MetachainConsensusGroupSize = 3, MetachainMinNumNodes = 3, Hysteresis = 0.0, Adaptivity = false, Offset = 2 }`,
	}
	for before, after := range replacements {
		require.Equal(t, 1, strings.Count(text, before))
		text = strings.Replace(text, before, after, 1)
	}
	require.NoError(t, os.WriteFile(configPath, []byte(text), 0o600))

	nodesPath := filepath.Join(packageRoot, "config", "nodesSetup.json")
	var nodesConfig config.NodesConfig
	require.NoError(t, core.LoadJsonFile(&nodesConfig, nodesPath))
	nodesConfig.StartTime = s0R3GenesisStart(t)
	if os.Getenv("S0_R3_GENESIS_START") != "" {
		require.GreaterOrEqual(t, nodesConfig.StartTime-time.Now().Unix(), int64(600), "fresh genesis operational buffer")
	}
	encoded, err := json.Marshal(nodesConfig)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(nodesPath, encoded, 0o600))
}

func materializeS0R3RuntimeInputs(t *testing.T, packageRoot string) {
	nodeBinary := os.Getenv("S0_R3_NODE_BINARY")
	seedBinary := os.Getenv("S0_R3_SEED_BINARY")
	require.NotEmpty(t, nodeBinary)
	require.NotEmpty(t, seedBinary)
	require.NoError(t, os.Mkdir(filepath.Join(packageRoot, "bin"), 0o700))
	copyFile(t, nodeBinary, filepath.Join(packageRoot, "bin", "node"), 0o700)
	copyFile(t, seedBinary, filepath.Join(packageRoot, "bin", "seednode"), 0o700)

	seedConfigRoot := filepath.Join(packageRoot, "seednode-runtime", "config")
	require.NoError(t, os.MkdirAll(seedConfigRoot, 0o700))
	copyFile(t, "../../cmd/seednode/config/config.toml", filepath.Join(seedConfigRoot, "config.toml"), 0o600)
	copyFile(t, "../../cmd/seednode/config/p2p.toml", filepath.Join(seedConfigRoot, "p2p.toml"), 0o600)

	p2pKeyRoot := filepath.Join(packageRoot, "p2p-keys")
	require.NoError(t, os.Mkdir(p2pKeyRoot, 0o700))
	seedPeerID := writeDeterministicP2PKey(t, filepath.Join(p2pKeyRoot, "seednode.pem"), "seednode")
	initialPeer := "/ip4/127.0.0.1/tcp/9999/p2p/" + seedPeerID
	p2pPath := filepath.Join(packageRoot, "config", "p2p.toml")
	p2pBytes, err := os.ReadFile(p2pPath)
	require.NoError(t, err)
	p2pText := string(p2pBytes)
	oldInitialPeer := "/ip4/127.0.0.1/tcp/9999/p2p/16Uiu2HAkw5SNNtSvH1zJiQ6Gc3WoGNSxiyNueRKe6fuAuh57G3Bk"
	require.Equal(t, 1, strings.Count(p2pText, oldInitialPeer))
	p2pText = strings.Replace(p2pText, oldInitialPeer, initialPeer, 1)
	require.NoError(t, os.WriteFile(p2pPath, []byte(p2pText), 0o600))

	processes := make([]s0R3ProcessBinding, 0, 20)
	setup := loadS0R3NodesSetup(t, packageRoot)
	var initial config.NodesConfig
	require.NoError(t, core.LoadJsonFile(&initial, filepath.Join(packageRoot, "config/nodesSetup.json")))
	validatorShards := make([]string, 0, len(initial.InitialNodes))
	for _, node := range initial.InitialNodes {
		key, err := hex.DecodeString(node.PubKey)
		require.NoError(t, err)
		shard, err := setup.GetShardIDForPubKey(key)
		require.NoError(t, err)
		name := strconv.FormatUint(uint64(shard), 10)
		if shard == core.MetachainShardId {
			name = "meta"
		}
		validatorShards = append(validatorShards, name)
	}
	for index, shard := range validatorShards {
		id := "validator-" + strconv.Itoa(index)
		p2pKey := filepath.Join("p2p-keys", id+".pem")
		writeDeterministicP2PKey(t, filepath.Join(packageRoot, p2pKey), id)
		processes = append(processes, s0R3ProcessBinding{
			ID: id, Role: "validator", Shard: shard, KeyFile: "allValidatorsKeys.pem", KeyIndex: index,
			P2PKeyFile: p2pKey, APIPort: 9500 + index, P2PPort: 21500 + index,
			WorkingDirectory: ".",
			Argv:             []string{"bin/node", "-port", strconv.Itoa(21500 + index), "-rest-api-interface", "localhost:" + strconv.Itoa(9500+index), "-validator-key-pem-file", "allValidatorsKeys.pem", "-sk-index", strconv.Itoa(index), "-p2p-key-pem-file", p2pKey, "-working-directory", "runtime/" + id, "-config", "config/config.toml"},
		})
	}
	observerShards := []string{"meta", "0", "1", "2"}
	for index, shard := range observerShards {
		id := "observer-" + shard
		destination := shard
		if shard == "meta" {
			destination = "metachain"
		}
		p2pKey := filepath.Join("p2p-keys", id+".pem")
		writeDeterministicP2PKey(t, filepath.Join(packageRoot, p2pKey), id)
		processes = append(processes, s0R3ProcessBinding{
			ID: id, Role: "observer", Shard: shard, KeyFile: "config/testKeys/extraValidatorsKeys.pem", KeyIndex: index,
			P2PKeyFile: p2pKey, APIPort: 10000 + index, P2PPort: 21100 + index,
			WorkingDirectory: ".",
			Argv:             []string{"bin/node", "-port", strconv.Itoa(21100 + index), "-rest-api-interface", "localhost:" + strconv.Itoa(10000+index), "-destination-shard-as-observer", destination, "-validator-key-pem-file", "config/testKeys/extraValidatorsKeys.pem", "-sk-index", strconv.Itoa(index), "-p2p-key-pem-file", p2pKey, "-working-directory", "runtime/" + id, "-config", "config/config.toml", "-operation-mode", "db-lookup-extension"},
		})
	}
	inventory := s0R3ProcessInventory{
		SchemaVersion: "1.1.0", PackageClass: "NON_RUNNING_LOCALNET_INPUTS",
		SourceCommit: s0R3RequiredIdentity(t, "S0_R3_SOURCE_COMMIT"), SourceTree: s0R3RequiredIdentity(t, "S0_R3_SOURCE_TREE"),
		NodeBinarySHA256: fileSHA256(t, nodeBinary), SeedBinarySHA256: fileSHA256(t, seedBinary),
		ConfigurationRoot: "config", WorkingDirConvention: "package-root-relative per-process workingDirectory",
		ChainID: "local-testnet", GenesisStartTime: s0R3GenesisStart(t), Processes: processes,
		SupportProcesses: []s0R3ProcessBinding{{ID: "seednode", Role: "seednode", Shard: "none", P2PKeyFile: "p2p-keys/seednode.pem", APIPort: 9998, P2PPort: 9999, WorkingDirectory: "seednode-runtime", Argv: []string{"../bin/seednode", "-port", "9999", "-rest-api-interface", "localhost:9998", "-config", "config/config.toml", "-p2p-key-pem-file", "../p2p-keys/seednode.pem"}}},
	}
	encoded, err := json.MarshalIndent(inventory, "", "  ")
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(packageRoot, "process-inventory.json"), append(encoded, '\n'), 0o600))
}

func writeDeterministicP2PKey(t *testing.T, path, identity string) string {
	digest := sha256.Sum256([]byte("S0-R3-P2P-KEY-v1/" + identity))
	keyGenerator := signing.NewKeyGenerator(secp256k1.NewSecp256k1())
	privateKey, err := keyGenerator.PrivateKeyFromByteArray(digest[:])
	require.NoError(t, err)
	privateBytes, err := privateKey.ToByteArray()
	require.NoError(t, err)
	peerID, err := p2pFactory.NewP2PKeyConverter().ConvertPublicKeyToPeerID(privateKey.GeneratePublic())
	require.NoError(t, err)
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	require.NoError(t, err)
	// SaveSkToPemFile wraps its input verbatim; the real P2P loader hex-decodes it.
	require.NoError(t, core.SaveSkToPemFile(file, peerID.Pretty(), []byte(hex.EncodeToString(privateBytes))))
	require.NoError(t, file.Close())
	return peerID.Pretty()
}

func copyFile(t *testing.T, source, destination string, mode os.FileMode) {
	input, err := os.Open(source)
	require.NoError(t, err)
	defer input.Close()
	output, err := os.OpenFile(destination, os.O_WRONLY|os.O_CREATE|os.O_EXCL, mode)
	require.NoError(t, err)
	_, err = io.Copy(output, input)
	require.NoError(t, err)
	require.NoError(t, output.Close())
}

func fileSHA256(t *testing.T, path string) string {
	file, err := os.Open(path)
	require.NoError(t, err)
	defer file.Close()
	digest := sha256.New()
	_, err = io.Copy(digest, file)
	require.NoError(t, err)
	return hex.EncodeToString(digest.Sum(nil))
}

func TestS0RealLoaderNonRunningPackage(t *testing.T) {
	packageRoot := os.Getenv("S0_R3_PACKAGE_ROOT")
	if packageRoot == "" {
		t.Skip("S0_R3_PACKAGE_ROOT is required for retained package verification")
	}
	configRoot := filepath.Join(packageRoot, "config")

	mainConfig, err := commonConfig.LoadMainConfig(filepath.Join(configRoot, "config.toml"))
	require.NoError(t, err)
	require.Equal(t, "local-testnet", mainConfig.GeneralSettings.ChainID)
	require.Equal(t, uint32(3), mainConfig.GeneralSettings.GenesisMaxNumberOfShards)
	require.Len(t, mainConfig.GeneralSettings.ChainParametersByEpoch, 3)
	expectedGeometry := []config.ChainParametersByEpochConfig{
		{EnableEpoch: 0, RoundDuration: 6000, RoundsPerEpoch: 200, MinRoundsBetweenEpochs: 20, ShardConsensusGroupSize: 3, ShardMinNumNodes: 3, MetachainConsensusGroupSize: 3, MetachainMinNumNodes: 3},
		{EnableEpoch: 1, RoundDuration: 6000, RoundsPerEpoch: 200, MinRoundsBetweenEpochs: 20, ShardConsensusGroupSize: 3, ShardMinNumNodes: 3, MetachainConsensusGroupSize: 3, MetachainMinNumNodes: 3},
		{EnableEpoch: 2, RoundDuration: 600, RoundsPerEpoch: 2000, MinRoundsBetweenEpochs: 50, ShardConsensusGroupSize: 3, ShardMinNumNodes: 3, MetachainConsensusGroupSize: 3, MetachainMinNumNodes: 3, Offset: 2},
	}
	for index, expected := range expectedGeometry {
		actual := mainConfig.GeneralSettings.ChainParametersByEpoch[index]
		require.Equal(t, expected, actual)
		require.False(t, actual.Adaptivity)
		require.Zero(t, actual.Hysteresis)
	}

	_, err = commonConfig.LoadApiConfig(filepath.Join(configRoot, "api.toml"))
	require.NoError(t, err)
	_, err = commonConfig.LoadEconomicsConfig(filepath.Join(configRoot, "economics.toml"))
	require.NoError(t, err)
	_, err = commonConfig.LoadSystemSmartContractsConfig(filepath.Join(configRoot, "systemSmartContractsConfig.toml"))
	require.NoError(t, err)
	_, err = commonConfig.LoadRatingsConfig(filepath.Join(configRoot, "ratings.toml"))
	require.NoError(t, err)
	_, err = commonConfig.LoadPreferencesConfig(filepath.Join(configRoot, "prefs.toml"))
	require.NoError(t, err)
	_, err = commonConfig.LoadP2PConfig(filepath.Join(configRoot, "p2p.toml"))
	require.NoError(t, err)
	_, err = commonConfig.LoadP2PConfig(filepath.Join(configRoot, "fullArchiveP2P.toml"))
	require.NoError(t, err)
	_, err = commonConfig.LoadExternalConfig(filepath.Join(configRoot, "external.toml"))
	require.NoError(t, err)
	epochConfig, err := commonConfig.LoadEpochConfig(filepath.Join(configRoot, "enableEpochs.toml"))
	require.NoError(t, err)
	require.Equal(t, uint32(2), epochConfig.EnableEpochs.SupernovaEnableEpoch)
	require.Equal(t, []config.MaxNodesChangeConfig{{EpochEnable: 0, MaxNumNodes: 48, NodesToShufflePerShard: 4}, {EpochEnable: 1, MaxNumNodes: 64, NodesToShufflePerShard: 2}, {EpochEnable: 3, MaxNumNodes: 56, NodesToShufflePerShard: 2}}, epochConfig.EnableEpochs.MaxNodesChangeEnableEpoch)
	system, err := commonConfig.LoadSystemSmartContractsConfig(filepath.Join(configRoot, "systemSmartContractsConfig.toml"))
	require.NoError(t, err)
	require.Equal(t, uint64(64), system.StakingSystemSCConfig.MaxNumberOfNodesForStake)
	require.Len(t, epochConfig.GasSchedule.GasScheduleByEpochs, 1)
	require.Equal(t, uint32(0), epochConfig.GasSchedule.GasScheduleByEpochs[0].StartEpoch)
	require.Equal(t, "gasScheduleV9.toml", epochConfig.GasSchedule.GasScheduleByEpochs[0].FileName)
	roundConfig, err := commonConfig.LoadRoundConfig(filepath.Join(configRoot, "enableRounds.toml"))
	require.NoError(t, err)
	require.Equal(t, "440", roundConfig.RoundActivations["SupernovaEnableRound"].Round)
	_, err = commonConfig.LoadGasScheduleConfig(filepath.Join(configRoot, "gasSchedules", "gasScheduleV9.toml"))
	require.NoError(t, err)

	var nodesConfig config.NodesConfig
	require.NoError(t, core.LoadJsonFile(&nodesConfig, filepath.Join(configRoot, "nodesSetup.json")))
	require.Equal(t, s0R3GenesisStart(t), nodesConfig.StartTime)
	require.Len(t, nodesConfig.InitialNodes, 16)
	addressConverter, err := commonFactory.NewPubkeyConverter(mainConfig.AddressPubkeyConverter)
	require.NoError(t, err)
	validatorConverter, err := commonFactory.NewPubkeyConverter(mainConfig.ValidatorPubkeyConverter)
	require.NoError(t, err)
	provider := &chainParameters.ChainParametersHandlerStub{
		ChainParametersForEpochCalled: func(epoch uint32) (config.ChainParametersByEpochConfig, error) {
			require.Zero(t, epoch)
			return mainConfig.GeneralSettings.ChainParametersByEpoch[0], nil
		},
	}
	nodesSetup, err := sharding.NewNodesSetup(nodesConfig, provider, addressConverter, validatorConverter, 3)
	require.NoError(t, err)
	require.NoError(t, config.SanityCheckNodesConfig(nodesSetup, epochConfig.EnableEpochs))
	require.Equal(t, uint32(3), nodesSetup.NumberOfShards())
	require.Equal(t, uint32(12), nodesSetup.MinNumberOfNodes())
	eligible, waiting := nodesSetup.InitialNodesInfo()
	require.Len(t, waiting, 4)
	for _, shardID := range []uint32{0, 1, 2, core.MetachainShardId} {
		require.Len(t, eligible[shardID], 3)
		require.Len(t, waiting[shardID], 1)
	}

	inventoryBytes, err := os.ReadFile(filepath.Join(packageRoot, "process-inventory.json"))
	require.NoError(t, err)
	var inventory s0R3ProcessInventory
	require.NoError(t, json.Unmarshal(inventoryBytes, &inventory))
	require.Equal(t, "1.1.0", inventory.SchemaVersion)
	require.Equal(t, "NON_RUNNING_LOCALNET_INPUTS", inventory.PackageClass)
	require.Equal(t, s0R3RequiredIdentity(t, "S0_R3_SOURCE_COMMIT"), inventory.SourceCommit)
	require.Equal(t, s0R3RequiredIdentity(t, "S0_R3_SOURCE_TREE"), inventory.SourceTree)
	require.Equal(t, fileSHA256(t, filepath.Join(packageRoot, "bin", "node")), inventory.NodeBinarySHA256)
	require.Equal(t, fileSHA256(t, filepath.Join(packageRoot, "bin", "seednode")), inventory.SeedBinarySHA256)
	require.Equal(t, "config", inventory.ConfigurationRoot)
	require.Equal(t, "package-root-relative per-process workingDirectory", inventory.WorkingDirConvention)
	require.Equal(t, mainConfig.GeneralSettings.ChainID, inventory.ChainID)
	require.Equal(t, nodesConfig.StartTime, inventory.GenesisStartTime)
	require.Len(t, inventory.Processes, 20)

	ids := make(map[string]struct{})
	apiPorts := make(map[int]struct{})
	p2pPorts := make(map[int]struct{})
	keyBindings := make(map[string]struct{})
	keyIdentities := make(map[string]struct{})
	p2pIdentities := make(map[string]struct{})
	for _, process := range inventory.Processes {
		validateS0R3ArgumentShape(t, process)
		require.NotEmpty(t, process.Argv)
		require.GreaterOrEqual(t, process.KeyIndex, 0)
		require.NotEmpty(t, process.ID)
		require.NotContains(t, ids, process.ID)
		ids[process.ID] = struct{}{}
		require.NotContains(t, apiPorts, process.APIPort)
		apiPorts[process.APIPort] = struct{}{}
		require.NotContains(t, p2pPorts, process.P2PPort)
		p2pPorts[process.P2PPort] = struct{}{}
		require.NotEqual(t, process.APIPort, process.P2PPort)
		require.Equal(t, ".", process.WorkingDirectory)
		require.Equal(t, filepath.Join(packageRoot, "bin", "node"), filepath.Clean(filepath.Join(packageRoot, process.WorkingDirectory, process.Argv[0])))

		keyPath := filepath.Join(packageRoot, process.KeyFile)
		keyTypes := pemBlockTypes(t, keyPath)
		require.Greater(t, len(keyTypes), process.KeyIndex)
		binding := process.KeyFile + ":" + strconv.Itoa(process.KeyIndex)
		require.NotContains(t, keyBindings, binding)
		keyBindings[binding] = struct{}{}
		keyIdentity := strings.TrimPrefix(keyTypes[process.KeyIndex], "PRIVATE KEY for ")
		require.NotContains(t, keyIdentities, keyIdentity)
		keyIdentities[keyIdentity] = struct{}{}
		p2pTypes := pemBlockTypes(t, filepath.Join(packageRoot, process.P2PKeyFile))
		require.Len(t, p2pTypes, 1)
		require.NotContains(t, p2pIdentities, p2pTypes[0])
		p2pIdentities[p2pTypes[0]] = struct{}{}
		require.Contains(t, process.Argv, process.P2PKeyFile)
		require.Contains(t, process.Argv, "localhost:"+strconv.Itoa(process.APIPort))
		require.Contains(t, process.Argv, strconv.Itoa(process.P2PPort))
		if process.Role == "validator" {
			require.Equal(t, "allValidatorsKeys.pem", process.KeyFile)
			require.Equal(t, nodesConfig.InitialNodes[process.KeyIndex].PubKey, keyIdentity)
			key, err := hex.DecodeString(keyIdentity)
			require.NoError(t, err)
			actualShard, err := nodesSetup.GetShardIDForPubKey(key)
			require.NoError(t, err)
			expectedShard := strconv.FormatUint(uint64(actualShard), 10)
			if actualShard == core.MetachainShardId {
				expectedShard = "meta"
			}
			require.Equal(t, expectedShard, process.Shard)
		} else {
			require.Equal(t, "observer", process.Role)
			require.Equal(t, "config/testKeys/extraValidatorsKeys.pem", process.KeyFile)
		}
	}
	require.Len(t, inventory.SupportProcesses, 1)
	seed := inventory.SupportProcesses[0]
	validateS0R3ArgumentShape(t, seed)
	require.NotEmpty(t, seed.Argv)
	require.Equal(t, "seednode", seed.Role)
	require.Equal(t, 9998, seed.APIPort)
	require.Equal(t, 9999, seed.P2PPort)
	require.Equal(t, "seednode-runtime", seed.WorkingDirectory)
	seedWorkingDirectory := filepath.Join(packageRoot, seed.WorkingDirectory)
	require.Equal(t, filepath.Join(packageRoot, "bin", "seednode"), filepath.Clean(filepath.Join(seedWorkingDirectory, seed.Argv[0])))
	seedConfigPath := filepath.Clean(filepath.Join(seedWorkingDirectory, argumentValue(t, seed.Argv, "-config")))
	require.Equal(t, filepath.Join(packageRoot, "seednode-runtime", "config", "config.toml"), seedConfigPath)
	_, err = commonConfig.LoadMainConfig(seedConfigPath)
	require.NoError(t, err)
	seedP2PConfigPath := filepath.Join(seedWorkingDirectory, "config", "p2p.toml")
	_, err = commonConfig.LoadP2PConfig(seedP2PConfigPath)
	require.NoError(t, err)
	seedKeyPath := filepath.Clean(filepath.Join(seedWorkingDirectory, argumentValue(t, seed.Argv, "-p2p-key-pem-file")))
	require.Equal(t, filepath.Join(packageRoot, seed.P2PKeyFile), seedKeyPath)
	seedP2PTypes := pemBlockTypes(t, filepath.Join(packageRoot, seed.P2PKeyFile))
	require.Len(t, seedP2PTypes, 1)
	require.NotContains(t, p2pIdentities, seedP2PTypes[0])
	p2pBytes, err := os.ReadFile(filepath.Join(configRoot, "p2p.toml"))
	require.NoError(t, err)
	seedPeerID := strings.TrimPrefix(seedP2PTypes[0], "PRIVATE KEY for ")
	require.Contains(t, string(p2pBytes), "/ip4/127.0.0.1/tcp/9999/p2p/"+seedPeerID)
	validateS0R3StartupInputs(t, packageRoot, mainConfig, nodesConfig, inventory)
}

// This NON_RUNNING package supports only the declared flags below. Reject
// additional real CLI overrides as well as unknown flags: otherwise validation
// of default config/genesis paths says nothing about the effective startup input.
func validateS0R3ArgumentShape(t *testing.T, process s0R3ProcessBinding) {
	t.Helper()
	allowed := []string{"-port", "-rest-api-interface", "-config", "-p2p-key-pem-file"}
	if process.Role == "validator" || process.Role == "observer" {
		allowed = append(allowed, "-validator-key-pem-file", "-sk-index", "-working-directory")
	} else {
		require.Equal(t, "seednode", process.Role)
	}
	if process.Role == "observer" {
		allowed = append(allowed, "-destination-shard-as-observer", "-operation-mode")
	}
	require.Len(t, process.Argv, 1+2*len(allowed), "exact bounded argv cardinality")
	seen := make(map[string]bool)
	for index := 1; index < len(process.Argv); index += 2 {
		flag := process.Argv[index]
		require.Contains(t, allowed, flag, "undeclared startup flag")
		require.False(t, seen[flag], "duplicate startup flag")
		seen[flag] = true
		require.NotEmpty(t, process.Argv[index+1], "empty startup value")
		require.False(t, strings.HasPrefix(process.Argv[index+1], "-"), "flag used as a value")
	}
}

func argumentValue(t *testing.T, arguments []string, name string) string {
	t.Helper()
	count := 0
	value := ""
	for index := 0; index < len(arguments); index++ {
		if arguments[index] == name {
			require.Less(t, index+1, len(arguments), "missing argument value: %s", name)
			count++
			value = arguments[index+1]
		}
	}
	require.Equal(t, 1, count, "argument must occur exactly once: %s", name)
	return value
}

// Validate with the same parsers and key decoders used by startup, not PEM labels
// or generated expectations alone. This is input validation, not a node launch.
func validateS0R3StartupInputs(t *testing.T, root string, cfg *config.Config, nodes config.NodesConfig, inv s0R3ProcessInventory) {
	t.Helper()
	economics, err := commonConfig.LoadEconomicsConfig(filepath.Join(root, "config/economics.toml"))
	require.NoError(t, err)
	address, err := commonFactory.NewPubkeyConverter(cfg.AddressPubkeyConverter)
	require.NoError(t, err)
	hasher, err := hashFactory.NewHasher(cfg.Hasher.Type)
	require.NoError(t, err)
	marshalizer, err := marshalFactory.NewMarshalizer(cfg.Marshalizer.Type)
	require.NoError(t, err)
	supply, ok := new(big.Int).SetString(economics.GlobalSettings.GenesisTotalSupply, 10)
	require.True(t, ok, "invalid genesis supply")
	require.Positive(t, supply.Sign())
	wallets := signing.NewKeyGenerator(ed25519.NewEd25519())
	_, err = parsing.NewAccountsParser(genesis.AccountsParserArgs{
		GenesisFilePath: filepath.Join(root, "config/genesis.json"), EntireSupply: supply,
		MinterAddress:   economics.GlobalSettings.GenesisMintingSenderAddress,
		PubkeyConverter: address, KeyGenerator: wallets, Hasher: hasher, Marshalizer: marshalizer,
	})
	require.NoError(t, err)
	contracts, err := parsing.NewSmartContractsParser(filepath.Join(root, "config/genesisSmartContracts.json"), address, wallets)
	require.NoError(t, err)
	require.Empty(t, contracts.InitialSmartContracts(), "this simulator-derived baseline fixture intentionally has no genesis contracts")

	bls := signing.NewKeyGenerator(mcl.NewSuiteBLS12())
	secp := signing.NewKeyGenerator(secp256k1.NewSecp256k1())
	ports, directories, peers := map[int]bool{}, map[string]bool{}, map[string]bool{}
	validators, observers := map[string]bool{}, map[string]bool{}
	for _, node := range nodes.InitialNodes {
		validators[node.PubKey] = true
	}
	for _, process := range append(append([]s0R3ProcessBinding{}, inv.Processes...), inv.SupportProcesses...) {
		cwd := filepath.Join(root, process.WorkingDirectory)
		require.Equal(t, strconv.Itoa(process.P2PPort), argumentValue(t, process.Argv, "-port"))
		require.Equal(t, "localhost:"+strconv.Itoa(process.APIPort), argumentValue(t, process.Argv, "-rest-api-interface"))
		for _, port := range []int{process.P2PPort, process.APIPort} {
			require.True(t, port > 0 && port <= 65535, "invalid port")
			require.False(t, ports[port], "API/P2P port collision")
			ports[port] = true
		}
		keyPath := filepath.Clean(filepath.Join(cwd, argumentValue(t, process.Argv, "-p2p-key-pem-file")))
		require.Equal(t, filepath.Join(root, process.P2PKeyFile), keyPath)
		privateBytes, err := commonConfig.GetSkBytesFromP2pKey(keyPath)
		require.NoError(t, err)
		// Missing files otherwise select random-key fallback at real startup.
		require.NotEmpty(t, privateBytes, "missing pinned P2P key")
		private, err := secp.PrivateKeyFromByteArray(privateBytes)
		require.NoError(t, err)
		peer, err := p2pFactory.NewP2PKeyConverter().ConvertPublicKeyToPeerID(private.GeneratePublic())
		require.NoError(t, err)
		_, label, err := core.LoadSkPkFromPemFile(keyPath, 0)
		require.NoError(t, err)
		require.Equal(t, peer.Pretty(), label, "P2P body/label mismatch")
		require.False(t, peers[label], "duplicate P2P identity")
		peers[label] = true
		if process.Role == "seednode" {
			continue
		}
		require.Equal(t, "config/config.toml", argumentValue(t, process.Argv, "-config"))
		require.Equal(t, process.KeyFile, argumentValue(t, process.Argv, "-validator-key-pem-file"))
		require.Equal(t, strconv.Itoa(process.KeyIndex), argumentValue(t, process.Argv, "-sk-index"))
		require.Equal(t, "runtime/"+process.ID, argumentValue(t, process.Argv, "-working-directory"))
		directory := filepath.Join(cwd, argumentValue(t, process.Argv, "-working-directory"))
		require.False(t, directories[directory], "duplicate database root")
		directories[directory] = true
		encoded, label, err := core.LoadSkPkFromPemFile(filepath.Join(cwd, process.KeyFile), process.KeyIndex)
		require.NoError(t, err)
		decoded, err := hex.DecodeString(string(encoded))
		require.NoError(t, err)
		blsPrivate, err := bls.PrivateKeyFromByteArray(decoded)
		require.NoError(t, err)
		public, err := blsPrivate.GeneratePublic().ToByteArray()
		require.NoError(t, err)
		require.Equal(t, hex.EncodeToString(public), label, "BLS body/label mismatch")
		if process.Role == "validator" {
			require.Equal(t, nodes.InitialNodes[process.KeyIndex].PubKey, label)
		} else {
			require.False(t, validators[label], "observer is genesis validator")
			require.Contains(t, []string{"meta", "0", "1", "2"}, process.Shard)
			require.False(t, observers[process.Shard], "duplicate observer shard")
			observers[process.Shard] = true
			destination := process.Shard
			if destination == "meta" {
				destination = "metachain"
			}
			require.Equal(t, destination, argumentValue(t, process.Argv, "-destination-shard-as-observer"))
			require.Equal(t, "db-lookup-extension", argumentValue(t, process.Argv, "-operation-mode"))
		}
	}
	require.Len(t, peers, 21)
	require.Len(t, ports, 42)
	require.Len(t, directories, 20)
	require.Len(t, observers, 4)
}

func pemBlockTypes(t *testing.T, path string) []string {
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	types := make([]string, 0)
	for len(data) > 0 {
		block, rest := pem.Decode(data)
		require.NotNil(t, block)
		types = append(types, block.Type)
		data = rest
	}
	return types
}

func TestS0R3StartupInputHostiles(t *testing.T) {
	source := os.Getenv("S0_R3_PACKAGE_ROOT")
	if source == "" {
		t.Skip("S0_R3_PACKAGE_ROOT required")
	}
	root := filepath.Join(t.TempDir(), "package")
	require.NoError(t, filepath.Walk(source, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		require.Zero(t, info.Mode()&os.ModeSymlink, "no symlink fixture copies")
		rel, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		dest := filepath.Join(root, rel)
		if info.IsDir() {
			return os.MkdirAll(dest, 0o700)
		}
		require.True(t, info.Mode().IsRegular())
		copyFile(t, path, dest, info.Mode().Perm())
		return nil
	}))
	exe, err := os.Executable()
	require.NoError(t, err)
	runLoader := func(t *testing.T, wantPass bool) {
		t.Helper()
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, exe, "-test.run=^TestS0RealLoaderNonRunningPackage$", "-test.v")
		cmd.Env = append(os.Environ(), "S0_R3_PACKAGE_ROOT="+root)
		output, err := cmd.CombinedOutput()
		require.NoError(t, ctx.Err(), "timeout is not rejection evidence")
		if wantPass {
			require.NoError(t, err, "%s", output)
			require.Contains(t, string(output), "--- PASS: TestS0RealLoaderNonRunningPackage")
		} else {
			require.Error(t, err, "hostile package accepted")
			require.Contains(t, string(output), "--- FAIL: TestS0RealLoaderNonRunningPackage", "must fail an assertion, not crash")
			require.NotContains(t, string(output), "panic:")
		}
	}
	runLoader(t, true)
	mutateFile := func(t *testing.T, relative string, change func([]byte) []byte) {
		t.Helper()
		path := filepath.Join(root, relative)
		before, err := os.ReadFile(path)
		require.NoError(t, err)
		stat, err := os.Stat(path)
		require.NoError(t, err)
		t.Cleanup(func() { require.NoError(t, os.WriteFile(path, before, stat.Mode().Perm())) })
		after := change(append([]byte{}, before...))
		if after == nil {
			require.NoError(t, os.Remove(path))
		} else {
			require.NoError(t, os.WriteFile(path, after, stat.Mode().Perm()))
		}
		runLoader(t, false)
	}
	entries, err := os.ReadDir(filepath.Join(root, "p2p-keys"))
	require.NoError(t, err)
	require.Len(t, entries, 21)
	for _, entry := range entries {
		for _, mutation := range []string{"raw_not_hex", "malformed_hex", "wrong_label", "missing", "empty_key"} {
			t.Run("p2p/"+entry.Name()+"/"+mutation, func(t *testing.T) {
				mutateFile(t, "p2p-keys/"+entry.Name(), func(before []byte) []byte {
					if mutation == "missing" {
						return nil
					}
					block, _ := pem.Decode(before)
					require.NotNil(t, block)
					switch mutation {
					case "raw_not_hex":
						block.Bytes, err = hex.DecodeString(string(block.Bytes))
						require.NoError(t, err)
					case "malformed_hex":
						block.Bytes = []byte("not-hex")
					case "wrong_label":
						block.Type = "PRIVATE KEY for wrong-public-identity"
					case "empty_key":
						block.Bytes = []byte{}
					}
					return pem.EncodeToMemory(block)
				})
			})
		}
	}
	for _, relative := range []string{"config/genesis.json", "config/genesisSmartContracts.json", "seednode-runtime/config/config.toml", "seednode-runtime/config/p2p.toml"} {
		for _, mutation := range []string{"missing", "malformed"} {
			t.Run(relative+"/"+mutation, func(t *testing.T) {
				mutateFile(t, relative, func([]byte) []byte {
					if mutation == "missing" {
						return nil
					}
					return []byte("invalid[{")
				})
			})
		}
	}
	for _, relative := range []string{"allValidatorsKeys.pem", "config/testKeys/extraValidatorsKeys.pem"} {
		for _, mutation := range []string{"missing", "malformed_hex", "wrong_body"} {
			t.Run(relative+"/"+mutation, func(t *testing.T) {
				mutateFile(t, relative, func(before []byte) []byte {
					if mutation == "missing" {
						return nil
					}
					block, rest := pem.Decode(before)
					require.NotNil(t, block)
					if mutation == "malformed_hex" {
						block.Bytes = []byte("not-hex")
					} else {
						other, _ := pem.Decode(rest)
						require.NotNil(t, other)
						block.Bytes = other.Bytes
					}
					return append(pem.EncodeToMemory(block), rest...)
				})
			})
		}
	}
	for _, target := range []string{"validator", "waiting-validator", "observer", "seednode"} {
		// Source-declared node overrides and an unknown flag must never escape
		// this package's restricted argv contract, in append or replacement form.
		for _, flag := range []string{"-genesis-file", "-smart-contracts-file", "-nodes-setup-file", "-config-economics", "-config-api", "-config-systemSmartContracts", "-config-ratings", "-config-preferences", "-config-external", "-p2p-config", "-full-archive-p2p-config", "-epoch-config", "-round-config", "-gas-costs-config", "-unknown-startup-flag"} {
			for _, form := range []string{"append", "replace"} {
				t.Run("undeclared/"+target+"/"+flag+"/"+form, func(t *testing.T) {
					mutateFile(t, "process-inventory.json", func(before []byte) []byte {
						var inv s0R3ProcessInventory
						require.NoError(t, json.Unmarshal(before, &inv))
						p := &inv.Processes[0]
						if target == "waiting-validator" {
							p = &inv.Processes[12]
						}
						if target == "observer" {
							p = &inv.Processes[16]
						}
						if target == "seednode" {
							p = &inv.SupportProcesses[0]
						}
						if form == "append" {
							p.Argv = append(p.Argv, flag, "config/does-not-exist.json")
						} else {
							p.Argv[1] = flag
						}
						after, err := json.Marshal(inv)
						require.NoError(t, err)
						return after
					})
				})
			}
		}
		for _, mutation := range []string{"wrong_port", "wrong_api", "swapped_flags", "duplicate_flag", "missing_value", "wrong_p2p_path", "wrong_config"} {
			t.Run("argv/"+target+"/"+mutation, func(t *testing.T) {
				mutateFile(t, "process-inventory.json", func(before []byte) []byte {
					var inv s0R3ProcessInventory
					require.NoError(t, json.Unmarshal(before, &inv))
					p := &inv.Processes[0]
					if target == "waiting-validator" {
						p = &inv.Processes[12]
					}
					if target == "observer" {
						p = &inv.Processes[16]
					}
					if target == "seednode" {
						p = &inv.SupportProcesses[0]
					}
					replace := func(flag, value string) {
						for i := range p.Argv {
							if p.Argv[i] == flag {
								p.Argv[i+1] = value
								return
							}
						}
						t.Fatal("test flag absent")
					}
					switch mutation {
					case "wrong_port":
						replace("-port", "12345")
					case "wrong_api":
						replace("-rest-api-interface", "localhost:12345")
					case "swapped_flags":
						replace("-port", "localhost:"+strconv.Itoa(p.APIPort))
						replace("-rest-api-interface", strconv.Itoa(p.P2PPort))
					case "duplicate_flag":
						p.Argv = append(p.Argv, "-port", strconv.Itoa(p.P2PPort))
					case "missing_value":
						p.Argv = append(p.Argv, "-port")
					case "wrong_p2p_path":
						replace("-p2p-key-pem-file", "missing.pem")
					case "wrong_config":
						replace("-config", "config/missing.toml")
					}
					after, err := json.Marshal(inv)
					require.NoError(t, err)
					return after
				})
			})
		}
	}
	for _, mutation := range []string{"key_index", "negative_index", "key_path", "database", "observer_shard", "port_collision", "seed_cwd"} {
		t.Run("inventory/"+mutation, func(t *testing.T) {
			mutateFile(t, "process-inventory.json", func(before []byte) []byte {
				var inv s0R3ProcessInventory
				require.NoError(t, json.Unmarshal(before, &inv))
				p := &inv.Processes[0]
				for i := range p.Argv {
					if mutation == "key_index" && p.Argv[i] == "-sk-index" {
						p.Argv[i+1] = "1"
					}
					if mutation == "key_path" && p.Argv[i] == "-validator-key-pem-file" {
						p.Argv[i+1] = "missing.pem"
					}
					if mutation == "database" && p.Argv[i] == "-working-directory" {
						p.Argv[i+1] = "runtime/validator-1"
					}
				}
				if mutation == "negative_index" {
					p.KeyIndex = -1
				}
				if mutation == "observer_shard" {
					inv.Processes[16].Shard = "0"
				}
				if mutation == "seed_cwd" {
					inv.SupportProcesses[0].WorkingDirectory = "."
				}
				if mutation == "port_collision" {
					p.P2PPort = inv.Processes[1].APIPort
					for i := range p.Argv {
						if p.Argv[i] == "-port" {
							p.Argv[i+1] = strconv.Itoa(p.P2PPort)
						}
					}
				}
				after, err := json.Marshal(inv)
				require.NoError(t, err)
				return after
			})
		})
	}
	runLoader(t, true)
}

func runS0R3Simulator(t *testing.T) s0R3SimulatorSnapshot {
	// Deterministic-key overlay is intentionally not part of current source.

	simulator, err := NewChainSimulator(ArgsChainSimulator{
		BypassTxSignatureCheck:         true,
		BypassCreateBlockTimeCheck:     true,
		TempDir:                        t.TempDir(),
		PathToInitialConfig:            "../../cmd/node/config/",
		NumOfShards:                    3,
		RoundDurationInMillis:          6000,
		SupernovaRoundDurationInMillis: 600,
		RoundsPerEpoch:                 core.OptionalUint64{HasValue: true, Value: 20},
		SupernovaRoundsPerEpoch:        core.OptionalUint64{HasValue: true, Value: 40},
		ApiInterface:                   api.NewNoApiInterface(),
		MinNodesPerShard:               1,
		MetaChainMinNodes:              1,
		GenesisTimestamp:               1700000000,
	})
	require.NoError(t, err)
	defer simulator.Close()

	require.NoError(t, simulator.GenerateBlocks(12))

	snapshot := s0R3SimulatorSnapshot{
		TerminalNonces: make(map[uint32]uint64),
		TerminalRounds: make(map[uint32]uint64),
		StateRoots:     make(map[uint32]string),
	}
	for _, privateKey := range simulator.GetValidatorPrivateKeys() {
		publicKey, errPublic := privateKey.GeneratePublic().ToByteArray()
		require.NoError(t, errPublic)
		snapshot.ValidatorPublicKeys = append(snapshot.ValidatorPublicKeys, hex.EncodeToString(publicKey))
	}
	sort.Strings(snapshot.ValidatorPublicKeys)

	wallets := simulator.GetInitialWalletKeys()
	for _, wallet := range wallets.StakeWallets {
		snapshot.WalletPublicKeys = append(snapshot.WalletPublicKeys, hex.EncodeToString(wallet.Address.Bytes))
	}
	for _, wallet := range wallets.BalanceWallets {
		snapshot.WalletPublicKeys = append(snapshot.WalletPublicKeys, hex.EncodeToString(wallet.Address.Bytes))
	}
	sort.Strings(snapshot.WalletPublicKeys)

	for _, shardID := range []uint32{0, 1, 2, core.MetachainShardId} {
		chain := simulator.GetNodeHandler(shardID).GetChainHandler()
		header := chain.GetCurrentBlockHeader()
		require.NotNil(t, header)
		snapshot.TerminalNonces[shardID] = header.GetNonce()
		snapshot.TerminalRounds[shardID] = header.GetRound()
		snapshot.StateRoots[shardID] = hex.EncodeToString(chain.GetCurrentBlockRootHash())
	}

	return snapshot
}

func s0R3RequiredIdentity(t *testing.T, name string) string {
	t.Helper()
	value := os.Getenv(name)
	require.Len(t, value, 40, "%s must be an exact Git object identity", name)
	_, err := hex.DecodeString(value)
	require.NoError(t, err, "%s must be hexadecimal", name)
	return value
}

func s0R3GenesisStart(t *testing.T) int64 {
	t.Helper()
	value := os.Getenv("S0_R3_GENESIS_START")
	if value == "" {
		return 1900000000
	}
	stamp, err := strconv.ParseInt(value, 10, 64)
	require.NoError(t, err)
	require.Positive(t, stamp)
	return stamp
}

func loadS0R3NodesSetup(t *testing.T, root string) *sharding.NodesSetup {
	t.Helper()
	cfg, err := commonConfig.LoadMainConfig(filepath.Join(root, "config/config.toml"))
	require.NoError(t, err)
	var initial config.NodesConfig
	require.NoError(t, core.LoadJsonFile(&initial, filepath.Join(root, "config/nodesSetup.json")))
	address, err := commonFactory.NewPubkeyConverter(cfg.AddressPubkeyConverter)
	require.NoError(t, err)
	validator, err := commonFactory.NewPubkeyConverter(cfg.ValidatorPubkeyConverter)
	require.NoError(t, err)
	provider := &chainParameters.ChainParametersHandlerStub{ChainParametersForEpochCalled: func(epoch uint32) (config.ChainParametersByEpochConfig, error) {
		require.Zero(t, epoch)
		return cfg.GeneralSettings.ChainParametersByEpoch[0], nil
	}}
	setup, err := sharding.NewNodesSetup(initial, provider, address, validator, cfg.GeneralSettings.GenesisMaxNumberOfShards)
	require.NoError(t, err)
	return setup
}

func TestS0R3WaitingPoolReassignment(t *testing.T) {
	root := os.Getenv("S0_R3_PACKAGE_ROOT")
	if root == "" {
		t.Skip("S0_R3_PACKAGE_ROOT is required for reassignment qualification")
	}
	setup := loadS0R3NodesSetup(t, root)
	initialEligible, initialWaiting := setup.InitialNodesInfo()
	convert := func(input map[uint32][]nodesCoordinator.GenesisNodeInfoHandler) map[uint32][]nodesCoordinator.Validator {
		result := make(map[uint32][]nodesCoordinator.Validator)
		for shard, list := range input {
			for i, node := range list {
				v, err := nodesCoordinator.NewValidator(node.PubKeyBytes(), 1, uint32(i))
				require.NoError(t, err)
				result[shard] = append(result[shard], v)
			}
		}
		return result
	}
	snapshot := func(input map[uint32][]nodesCoordinator.Validator) map[string]uint32 {
		result := make(map[string]uint32)
		for shard, list := range input {
			for _, v := range list {
				key := hex.EncodeToString(v.PubKey())
				require.NotContains(t, result, key)
				result[key] = shard
			}
		}
		return result
	}
	eligible, waiting := convert(initialEligible), convert(initialWaiting)
	cfg, err := commonConfig.LoadMainConfig(filepath.Join(root, "config/config.toml"))
	require.NoError(t, err)
	epochs, err := commonConfig.LoadEpochConfig(filepath.Join(root, "config/enableEpochs.toml"))
	require.NoError(t, err)
	handler, err := enablers.NewEnableEpochsHandler(epochs.EnableEpochs, &epochNotifier.EpochNotifierStub{})
	require.NoError(t, err)
	shuffler, err := nodesCoordinator.NewHashValidatorsShuffler(&nodesCoordinator.NodesShufflerArgs{ShuffleBetweenShards: true, MaxNodesEnableConfig: epochs.EnableEpochs.MaxNodesChangeEnableEpoch, EnableEpochs: epochs.EnableEpochs, EnableEpochsHandler: handler})
	require.NoError(t, err)
	movedTotal := 0
	for epoch := uint32(1); epoch <= 4; epoch++ {
		handler.EpochConfirmed(epoch, 0)
		params := cfg.GeneralSettings.ChainParametersByEpoch[0]
		for _, candidate := range cfg.GeneralSettings.ChainParametersByEpoch {
			if candidate.EnableEpoch <= epoch {
				params = candidate
			}
		}
		random := sha256.Sum256([]byte(fmt.Sprintf("S0-R3-offline-waiting-route/%d", epoch)))
		args := nodesCoordinator.ArgsUpdateNodes{ChainParameters: params, Eligible: eligible, Waiting: waiting, Rand: random[:], NbShards: 3, Epoch: epoch}
		first, err := shuffler.UpdateNodeLists(args)
		require.NoError(t, err)
		second, err := shuffler.UpdateNodeLists(args)
		require.NoError(t, err)
		require.Equal(t, snapshot(first.Eligible), snapshot(second.Eligible))
		require.Equal(t, snapshot(first.Waiting), snapshot(second.Waiting))
		before := snapshot(eligible)
		for k, v := range snapshot(waiting) {
			require.NotContains(t, before, k)
			before[k] = v
		}
		after := snapshot(first.Eligible)
		for k, v := range snapshot(first.Waiting) {
			require.NotContains(t, after, k)
			after[k] = v
		}
		require.Len(t, before, 16)
		require.Len(t, after, 16)
		moved := 0
		for key, shard := range before {
			target, ok := after[key]
			require.True(t, ok)
			if shard != target {
				moved++
			}
		}
		for _, shard := range []uint32{0, 1, 2, core.MetachainShardId} {
			require.Len(t, first.Eligible[shard], 3)
			require.Len(t, first.Waiting[shard], 1)
			require.Len(t, first.ShuffledOut[shard], 1)
		}
		movedTotal += moved
		t.Logf("OFFLINE_SHUFFLER epoch=%d validators=16 waiting=4 cross_shard_moves=%d", epoch, moved)
		eligible, waiting = first.Eligible, first.Waiting
	}
	require.Positive(t, movedTotal, "must demonstrate an actual source-shuffler reassignment route")
	// Independently retain the inherited no-waiting counterexample: no surplus means no validator can rotate.
	handler.EpochConfirmed(1, 0)
	original := convert(initialEligible)
	negative, err := shuffler.UpdateNodeLists(nodesCoordinator.ArgsUpdateNodes{ChainParameters: cfg.GeneralSettings.ChainParametersByEpoch[0], Eligible: original, Waiting: map[uint32][]nodesCoordinator.Validator{}, Rand: []byte("no waiting counterexample"), NbShards: 3, Epoch: 1})
	require.NoError(t, err)
	require.Equal(t, snapshot(original), snapshot(negative.Eligible))
	require.Empty(t, snapshot(negative.ShuffledOut))
}

// The canonical epoch producer and block API use this same V1/V3 root selection.
// This checks byte/anchor consistency only; the caller must separately establish
// provenance from the running generation and agreement of metachain witnesses.
func verifyS0R3EpochHeaderAnchors(metaRaw []byte, shardRaw map[uint32][]byte, epoch uint32, chainID string) error {
	marshalizer, err := marshalFactory.NewMarshalizer("gogo protobuf")
	if err != nil {
		return err
	}
	hasher, err := hashFactory.NewHasher("blake2b")
	if err != nil {
		return err
	}
	meta, err := process.UnmarshalMetaHeader(marshalizer, metaRaw)
	if err != nil {
		return err
	}
	if meta.GetEpoch() != epoch || !meta.IsStartOfEpochBlock() || string(meta.GetChainID()) != chainID {
		return fmt.Errorf("wrong epoch, chain or non-epoch header")
	}
	anchors := meta.GetEpochStartHandler().GetLastFinalizedHeaderHandlers()
	if len(anchors) != 3 || len(shardRaw) != 3 {
		return fmt.Errorf("three shard anchors and bodies required")
	}
	seen := map[uint32]bool{}
	for _, anchor := range anchors {
		id := anchor.GetShardID()
		if id > 2 || seen[id] {
			return fmt.Errorf("invalid or duplicate shard anchor")
		}
		seen[id] = true
		raw, exists := shardRaw[id]
		if !exists || len(raw) == 0 {
			return fmt.Errorf("missing shard bytes")
		}
		if !bytes.Equal(hasher.Compute(string(raw)), anchor.GetHeaderHash()) {
			return fmt.Errorf("shard header hash mismatch")
		}
		header, err := process.UnmarshalShardHeader(marshalizer, raw)
		if err != nil {
			return err
		}
		if header.GetShardID() != id || header.GetNonce() != anchor.GetNonce() || header.GetRound() != anchor.GetRound() || header.GetEpoch() != anchor.GetEpoch() || string(header.GetChainID()) != chainID {
			return fmt.Errorf("shard header identity mismatch")
		}
		root := header.GetRootHash()
		if header.IsHeaderV3() {
			last, ok := header.GetLastExecutionResultHandler().(data.LastShardExecutionResultHandler)
			if !ok || last == nil || last.IsInterfaceNil() || last.GetExecutionResultHandler() == nil || last.GetExecutionResultHandler().IsInterfaceNil() {
				return fmt.Errorf("missing V3 execution result")
			}
			root = last.GetExecutionResultHandler().GetRootHash()
		}
		if len(root) != 32 || !bytes.Equal(root, anchor.GetRootHash()) {
			return fmt.Errorf("finalized state root mismatch")
		}
	}
	return nil
}

func TestS0R3EpochHeaderAnchorContracts(t *testing.T) {
	// Fixtures are native upstream DTOs encoded by the pinned upstream marshaler.
	// Negative controls alter the independent raw-header/epoch-anchor boundary.
	marshalizer, err := marshalFactory.NewMarshalizer("gogo protobuf")
	require.NoError(t, err)
	hasher, err := hashFactory.NewHasher("blake2b")
	require.NoError(t, err)
	for _, version := range []int{1, 3} {
		t.Run(fmt.Sprintf("V%d", version), func(t *testing.T) {
			shards := map[uint32][]byte{}
			anchors := []block.EpochStartShardData{}
			epoch := uint32(1)
			if version == 3 {
				epoch = 3
			}
			for id := uint32(0); id < 3; id++ {
				root := bytes.Repeat([]byte{byte(id + 1)}, 32)
				var header data.HeaderHandler = &block.Header{ShardID: id, Epoch: epoch - 1, Nonce: 12, Round: 20, RootHash: root, ChainID: []byte("local-testnet")}
				if version == 3 {
					header = &block.HeaderV3{ShardID: id, Epoch: epoch - 1, Nonce: 12, Round: 20, ChainID: []byte("local-testnet"), LastExecutionResult: &block.ExecutionResultInfo{ExecutionResult: &block.BaseExecutionResult{RootHash: root, HeaderNonce: 11, HeaderRound: 19, HeaderEpoch: epoch - 1}}}
				}
				encoded, e := marshalizer.Marshal(header)
				require.NoError(t, e)
				shards[id] = encoded
				anchors = append(anchors, block.EpochStartShardData{ShardID: id, Epoch: epoch - 1, Nonce: 12, Round: 20, RootHash: root, HeaderHash: hasher.Compute(string(encoded))})
			}
			makeMeta := func(list []block.EpochStartShardData, requestedEpoch uint32, chain string) []byte {
				var meta data.MetaHeaderHandler = &block.MetaBlock{Epoch: requestedEpoch, Nonce: 40, Round: 60, ChainID: []byte(chain), EpochStart: block.EpochStart{LastFinalizedHeaders: list}}
				if version == 3 {
					meta = &block.MetaBlockV3{Epoch: requestedEpoch, Nonce: 40, Round: 60, ChainID: []byte(chain), EpochStart: block.EpochStart{LastFinalizedHeaders: list}, LastExecutionResult: &block.MetaExecutionResultInfo{ExecutionResult: &block.BaseMetaExecutionResult{BaseExecutionResult: &block.BaseExecutionResult{RootHash: bytes.Repeat([]byte{4}, 32)}}}}
				}
				raw, e := marshalizer.Marshal(meta)
				require.NoError(t, e)
				return raw
			}
			raw := makeMeta(anchors, epoch, "local-testnet")
			require.NoError(t, verifyS0R3EpochHeaderAnchors(raw, shards, epoch, "local-testnet"))
			if destination := os.Getenv("S0_R3_HEADER_FIXTURE_ROOT"); destination != "" {
				meta, e := process.UnmarshalMetaHeader(marshalizer, raw)
				require.NoError(t, e)
				payload, e := json.Marshal(struct {
					Epoch    uint32                 `json:"epoch"`
					Meta     []byte                 `json:"meta"`
					MetaJSON data.MetaHeaderHandler `json:"meta_json"`
					Shards   map[uint32][]byte      `json:"shards"`
				}{epoch, raw, meta, shards})
				require.NoError(t, e)
				file, e := os.OpenFile(filepath.Join(destination, fmt.Sprintf("V%d.json", version)), os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
				require.NoError(t, e)
				_, e = file.Write(payload)
				require.NoError(t, e)
				require.NoError(t, file.Close())
			}

			for _, kind := range []string{"wrong-root", "wrong-hash", "wrong-nonce", "wrong-round", "wrong-shard-epoch", "duplicate-shard", "missing-anchor", "wrong-chain", "wrong-meta-epoch", "missing-body", "mutated-body", "malformed-meta"} {
				t.Run(kind, func(t *testing.T) {
					copied := append([]block.EpochStartShardData{}, anchors...)
					bodies := map[uint32][]byte{}
					for k, v := range shards {
						bodies[k] = append([]byte{}, v...)
					}
					changedEpoch := epoch
					chain := "local-testnet"
					switch kind {
					case "wrong-root":
						copied[0].RootHash = bytes.Repeat([]byte{99}, 32)
					case "wrong-hash":
						copied[0].HeaderHash = bytes.Repeat([]byte{99}, 32)
					case "wrong-nonce":
						copied[0].Nonce++
					case "wrong-round":
						copied[0].Round++
					case "wrong-shard-epoch":
						copied[0].Epoch++
					case "duplicate-shard":
						copied[1].ShardID = 0
					case "missing-anchor":
						copied = copied[:2]
					case "wrong-chain":
						chain = "wrong-chain"
					case "wrong-meta-epoch":
						changedEpoch++
					case "missing-body":
						delete(bodies, 0)
					case "mutated-body":
						bodies[0][0] ^= 0xff
					}
					changed := makeMeta(copied, changedEpoch, chain)
					if kind == "malformed-meta" {
						changed = []byte{0xff}
					}
					require.Error(t, verifyS0R3EpochHeaderAnchors(changed, bodies, epoch, "local-testnet"))
				})
			}
		})
	}
}

func TestS0R3RetainedEpochHeaderAnchors(t *testing.T) {
	// Executed only read-only against a qx-capture-derived bundle, never a sender.
	path := os.Getenv("S0_R3_EPOCH_HEADER_BUNDLE")
	if path == "" {
		t.Skip("read-only runtime bundle not supplied")
	}
	var bundle struct {
		Epoch         uint32            `json:"epoch"`
		ChainID       string            `json:"chain_id"`
		MetaWitnesses [][]byte          `json:"meta_witnesses"`
		MetaJSON      json.RawMessage   `json:"meta_json"`
		ShardHeaders  map[uint32][]byte `json:"shard_headers"`
	}
	raw, err := os.ReadFile(path)
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(raw, &bundle))
	require.Len(t, bundle.MetaWitnesses, 3)
	require.NotEmpty(t, bundle.MetaWitnesses[0])
	for _, witness := range bundle.MetaWitnesses {
		require.Equal(t, bundle.MetaWitnesses[0], witness, "independent metachain responses disagree")
	}
	require.NoError(t, verifyS0R3EpochHeaderAnchors(bundle.MetaWitnesses[0], bundle.ShardHeaders, bundle.Epoch, bundle.ChainID))
	marshalizer, err := marshalFactory.NewMarshalizer("gogo protobuf")
	require.NoError(t, err)
	header, err := process.UnmarshalMetaHeader(marshalizer, bundle.MetaWitnesses[0])
	require.NoError(t, err)
	encoded, err := json.Marshal(header)
	require.NoError(t, err)
	require.JSONEq(t, string(encoded), string(bundle.MetaJSON), "raw and structured epoch header differ")

	t.Logf("S0_R3_EPOCH_HEADER_CONSISTENCY epoch=%d meta_witnesses=3 shard_anchors=3 bundle_sha256=%s", bundle.Epoch, fileSHA256(t, path))
}
