name: Code-coverage

on:
  push:
    branches:
      - NewArc
  pull_request:
    branches: [NewArc]

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    name: Build
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.2
          cache: false
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Get dependencies
        run: go mod download
      - name: Run unit tests
        run: |
          make test-coverage
